targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/schemas"
          output_folder: "lib/api-client-generated"
          separate_models: true
